// Run with: node tests/visitor-flow.cjs
const fs = require("node:fs");
const path = require("node:path");
const assert = require("node:assert/strict");

const root = path.join(__dirname, "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const visitor = fs.readFileSync(path.join(root, "visitor", "index.html"), "utf8");

assert.match(visitor, /index\.html\?flow=visitor/, "visitor URL starts the isolated visitor mode");
assert.match(html, /button\.dataset\.feedTab !== "latest"/, "only Latest is a public feed tab");
assert.match(html, /button\.dataset\.storyGroup !== "topStoriesWeek"/, "Top Stories This Week remains public");
assert.match(html, /function feedLatest\(\)[\s\S]*?filteredLatest\(\)\.slice\(0, 4\)[\s\S]*?caughtUpItem\(\)[\s\S]*?state\.topStoriesExpanded \? feed\.concat\(buildFeed\(state\.latestPosts\.slice\(4, 8\)\)\) : feed/, "visitors see the caught-up screen after four Latest posts and can continue into Top Stories");
assert.match(html, /function renderVisitorCaughtUpContent\(\)[\s\S]*?You’ve all caught up![\s\S]*?data-caught-up-carousel[\s\S]*?data-caught-up-signup[\s\S]*?data-caught-up-top-stories/, "the caught-up screen offers a four-slide member preview and its two visitor actions");
assert.match(html, /visitorCaughtUpHomepage[\s\S]*?visitorCaughtUpDigest[\s\S]*?visitorCaughtUpBookmarks[\s\S]*?visitorCaughtUpTopStories/, "the caught-up carousel uses all four supplied phone mockups");
assert.match(html, /function wireCaughtUpCarousel\(root\)[\s\S]*?carousel\.scrollTo/, "feature preview dots move the native horizontal carousel");
assert.match(html, /function openVisitorTopStories\(\)[\s\S]*?state\.topStoriesExpanded = true;[\s\S]*?state\.latestIndex = firstTopStoryIndex;[\s\S]*?vLatest\.snapCurrent\(true\)/, "Top Stories opens after the caught-up slide without leaving the reader");
assert.match(html, /onRequireLogin\(\{ type: "bookmark", postId: post\.id \}\)/, "bookmarking asks visitors to sign in");
assert.match(html, /onRequireLogin\(\{ type: "like", postId: post\.id \}\)/, "liking asks visitors to sign in");
assert.match(html, /action\.type === "bookmark" \? "Found something worth saving\?" : "Make your daily catch-up more relevant"/, "bookmark sign-up uses saving-focused copy");
assert.match(html, /bookmarked\.add\(pendingAction\.postId\)/, "the pending bookmark is restored after login");
assert.match(html, /likedPosts\.add\(pendingAction\.postId\)/, "the pending like is restored after login");
assert.match(html, /const category = pendingAction && pendingAction\.type === "category" \? pendingAction\.value : null;/, "login retains the requested category");
assert.match(html, /readerState\.storyGroup = category === "curated" \|\| category === "topics" \? null : category;/, "login restores protected story-group categories");
assert.match(html, /showCenterHint\("Exclusive features unlocked!\\nThank you for registering\."\)/, "login shows an account-unlocked message");
assert.match(html, /const showCategorySetup = category === "curated"[\s\S]*?showTopicSetup\(reader1\.showPersonalisedHint\)[\s\S]*?showRoleSetup\("peers", reader1\.showPersonalisedHint\)[\s\S]*?showRoleSetup\("sector", reader1\.showPersonalisedHint\)[\s\S]*?showRoleSetup\("industry", reader1\.showPersonalisedHint\)/, "protected categories show the in-reader personalised-content confirmation after setup");
assert.match(html, /role-setup-scrim(?!" data-close)/, "role-personalisation flow cannot be dismissed outside the sheet");
assert.match(html, /topic-setup-scrim" data-close[\s\S]*?addEventListener\("click", close\)/, "topic setup can be dismissed by clicking outside the sheet");
assert.match(html, /function showRegistrationComplete\(\)[\s\S]*?Registration complete[\s\S]*?Personalise my experience[\s\S]*?data-later/, "registration completion offers professional-context onboarding or a later choice");
assert.match(html, /function showHomeWelcome\(\)[\s\S]*?Welcome to GovInsider[\s\S]*?Show me around/, "returning home opens the welcome bottom sheet");
assert.match(html, /showCloseOnboarding\(showRegistrationComplete, \(\) => showScreen\("home"\)\)/, "exiting Fast Read shows registration completion only after profile onboarding is completed");
assert.match(html, /function completeLogin\(isSignUp = false\)[\s\S]*?else if \(isSignUp\) reader1\.showLoginHint\(\);/, "only sign-up shows the account-unlocked message");
assert.match(html, /data-auth-complete[\s\S]*?completeLogin\(true\)/, "sign-up actions are marked as account creation");
assert.match(html, /src="assets\/ph_confetti\.svg"/, "login notification uses the supplied confetti icon");
assert.match(html, /class="topstories-chevron" src="assets\/chevron\.svg"/, "category chevron uses the supplied SVG");
assert.match(html, /\.reader-bottombar\.content-ad\s*\{[\s\S]*?visibility: hidden;[\s\S]*?pointer-events: none;/, "ads hide controls without resizing the feed");
assert.match(html, /\.reader-bottombar\.event-only \.[\s\S]*?data-share/, "events retain only the share action in the bottom panel");
assert.match(html, /\.auth-back\s*\{[\s\S]*?width: max-content;[\s\S]*?padding: 16px;/, "Back button uses 16px padding on every side");
assert.match(html, /\.auth-title\s*\{[\s\S]*?font-size: 28px;[\s\S]*?line-height: 37px;/, "auth heading matches the Figma type scale");
assert.match(html, /authGoogle: "assets\/figma-auth-google\.svg"/, "auth uses the exported Figma provider icons");
assert.match(html, /onClose: \(\) => VISITOR_FLOW && isAuthenticated \? reader1\.showCloseOnboarding/, "profile onboarding runs only after a visitor authenticates");
assert.match(html, /function selectStoryGroup\(group\)[\s\S]*?VISITOR_FLOW && missingProfile[\s\S]*?showRoleSetup\(flow, \(\) => selectStoryGroup\(group\)\)/, "registered visitors complete missing profile data before opening peer, sector, or industry feeds");
assert.match(html, /const steps = requiredSteps\.filter\(\(step\) => !state\.profile\[step\.key\]\);[\s\S]*?steps\.forEach\(\(step, index\) => \{ state\.profile\[step\.key\] = selections\[index\]; \}\);/, "role setup requests and saves only the missing profile fields");
assert.match(html, /data-profile-first[\s\S]*?enterkeyhint="next"[\s\S]*?data-profile-last[\s\S]*?enterkeyhint="done"/, "name fields offer the appropriate mobile keyboard actions");
assert.match(html, /\.profile-onboarding\s*\{[\s\S]*?position: fixed;[\s\S]*?width: min\(100%, 430px\);/, "profile onboarding remains anchored to the viewport when the keyboard opens");
assert.doesNotMatch(html, /if \(isName\) overlay\.querySelector\("\[data-profile-first\]"\)\.focus\(\);/, "name onboarding does not autofocus and push itself above the keyboard");
assert.match(html, /const showCategorySetup = category === "curated"[\s\S]*?reader1\.showLoginHint\(\);\s*setTimeout\(showCategorySetup, 1400\);/, "protected categories show the reader toast before opening their setup sheet");
assert.match(html, /\.bottombar-icons\s+\[data-language-settings\]\s*\{\s*display:\s*none;/, "the language control remains in markup but is hidden in both flows");
assert.match(html, /\$\{VISITOR_FLOW \? "" : `<div class="summary-streak"/, "the streak section is omitted from the visitor flow");
assert.match(html, /if \(VISITOR_FLOW \|\| summaryStreakShown/, "visitor summaries do not update streak tracking");

console.log("PASS: visitor access, authentication, and pending bookmark handoff are wired");
